export const data = {
  name: "Moiz Usman Butt",
  city: "Lahore",
  country: "Pakistan",
  designation: "Senior Software Engineer",
  employer: "Devsinc",
  study: "BSSE",
  major: "Software Engineering",
  university: "University of Lahore",
  yearGraduated: "2022",
  titles: [
    {
      title: ["Senior Software Engineer"],
      autoStart: true,
      loop: true,
      pauseFor: 5000000,
    },
    {
      title: [
        "Javascript Enigneering",
        "React JS",
        "Sveltekit JS",
        "Next JS",
        "Cypress",
        "Google Chrome Extension",
      ],
      autoStart: true,
      loop: true,
      pauseFor: 1000,
    },
    {
      title: ["Python Engineering", "Django", "Flask", "Fast Api", "Scrapping", "Scripting"],
      autoStart: true,
      loop: true,
      pauseFor: 1000,
    },
  ],
  socials: {
    linkedin: "https://www.linkedin.com/in/moiz-butt-88172317b/",
    github: "https://github.com/Mr-Moeez/",
    instagram: "https://www.instagram.com/moiz.butt.977",
    whatsapp: +923349767086,
  },
  technologies: [
    "Python",
    "Javascript",
    "React",
    "Django",
    "Flask",
    "Postgres",
    "Sveltekit",
    "Aws",
    "Docker",
    "Next JS",
    "Node",
    "Mongo",
    "Jest",
    "Cypress",
  ],
};
