export const data = {
  name: "Mansi Bisht",
  city: "Dehradun",
  country: "India",
  designation: "B.Tech CSE (Data Science) Student",
  employer: "DIT University",
  study: "B.Tech",
  major: "Computer Science & Engineering (Data Science)",
  university: "DIT University, Dehradun",
  yearGraduated: "2026 (Expected)",
  titles: [
    {
      title: ["Web Developer"],
      autoStart: true,
      loop: true,
      pauseFor: 4000,
    },
    {
      title: [
        "React Developer",
        "Flutter Developer",
        "Full Stack Projects",
        "AI Integrations",
        "Machine Learning Enthusiast",
      ],
      autoStart: true,
      loop: true,
      pauseFor: 3000,
    },
    {
      title: [
        "Python Developer",
        "Flask",
        "SQLite",
        "OpenAI APIs",
        "TensorFlow",
      ],
      autoStart: true,
      loop: true,
      pauseFor: 3000,
    },
  ],
  socials: {
    linkedin: "https://www.linkedin.com/in/mansi-bisht-75805327b/",
    github: "https://github.com/mansicode12",
    gmail: "mailto:mansibisht14034@gmail.com",
    whatsapp: "+917830192450",
  },
  technologies: [
    "Python",
    "Java",
    "C",
    "JavaScript",
    "React",
    "Flutter",
    "Flask",
    "Node.js",
    "SQLite",
    "MongoDB",
    "MySQL",
    "Tailwind CSS",
    "TensorFlow",
    "HTML",
    "CSS",
    "Git",
    "NumPy",
    "Pandas",
    "Matplotlib",
  ],
};
